version: '2'
services:

  luigid:
    image: code-challenge/orchestrator:latest
    build:
      context: ./orchestrator
    command: luigid
    ports:
      - "8082:8082"

  orchestrator:
    image: code-challenge/orchestrator:latest
    depends_on:
      - luigid
    environment:
      - PROJECT_ROOT=$PWD
      - PIPELINE_VERSION=0.1
    volumes:
      - ./data_root:/usr/share/data/ # Mount data directory
      - /var/run/docker.sock:/var/run/docker.sock # Mount docker socker
      - ./orchestrator:/opt/orchestrator # Mount code for faster development
    build:
      context: ./orchestrator
    command: luigi --module task EvaluateModel --scheduler-host luigid
